### ISSUE TITLE
error installation

### ISSUE THREAD

**Issue by anasBahou** [mosheliv/tensortrt-yolo-python-api#5]
I've got this error :

jetson-nano@jetsonnano-desktop:~/deepstream_reference_apps/yolo/apps/trt-yolo/build$ cmake -D CMAKE_BUILD_TYPE=Release .. 

-- Found TensorRT headers at /usr/include/aarch64-linux-gnu
-- Found TensorRT libs at /usr/lib/aarch64-linux-gnu/libnvinfer.so;/usr/lib/aarch64-linux-gnu/libnvinfer_plugin.so
CMake Error at CMakeLists.txt:73 (add_subdirectory):
  add_subdirectory given source
  "/home/jetson-nano/deepstream_reference_apps/yolo/apps/../../lib" which is
  not an existing directory.

Please help me figure this out.

**Comment by mosheliv** [comment]
hmmm strange, it should refer to /home/jetson-nano/deepstream_reference_apps/yolo/lib and its going one level too high. 
Can you please try repeating the process from the start? removing the directory tree and recloning the deepstream repository? I think the problem is some cached cmake files.

**Comment by anasBahou** [comment]
thanks. It solved the problem
